djangotryout/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'djangotryout.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^todos/', include('todos.urls', namespace = "todos")),
    url(r'^admin/', include(admin.site.urls)),
)

todos/urls.py
from django.conf.urls import patterns, include, url

from todos import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<list_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<list_id>\d+)/complete/$', views.complete, name='complete'),
    url(r'^(?P<list_id>\d+)/add-item/$', views.add_item, name='add_item'),
)

todos/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class List(models.Model):
	title = models.CharField(max_length=140)
	description = models.TextField()
	creator = models.ForeignKey(User)
	def __str__(self):
		return self.title

	def completed_list_items(self):
		return self.item_set.filter(completed = True)

	def uncompleted_list_items(self):
		return self.item_set.filter(completed = False)

class Item(models.Model):
	name = models.CharField(max_length=140)
	description = models.TextField()
	list = models.ForeignKey(List)
	completed = models.BooleanField(default = False)
	def __str__(self):
		return self.name

todos/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import RequestContext, loader

from django.contrib.auth.models import User
from todos.models import List, Item

# Create your views here.

def index(request):
	todo_lists = List.objects.all()[:5]
	template = loader.get_template('todos/index.html')
	context = RequestContext(request, {'todo_lists': todo_lists})
	return HttpResponse(template.render(context))

def detail(request,list_id):
	list = get_object_or_404(List, pk=list_id)
	template = loader.get_template('todos/details.html')
	context = RequestContext(request, {'list': list})
	return HttpResponse(template.render(context))

def complete(request, list_id):
	list = get_object_or_404(List, pk=list_id)

	try:
		request.POST['item']
	except (KeyError, Item.DoesNotExist):
		return render(request, 'list/detail.html', {
            'list': list,
            'error_message': "You didn't select an item.",
        })
	else:
		for item_id in request.POST['item']:
			item = list.item_set.get(pk=item_id)
			item.completed = True
			item.save()
			print(item.completed)

		return HttpResponseRedirect(reverse('todos:detail', args=(list.id,)))

def add_item(request, list_id):
	list = get_object_or_404(List, pk=list_id)
	

todos/templates/todos/details.html
<h1>{{list.title}}</h1>
<div>
	<h3>Completed!</h3>
	<ul>
	{% for item in list.completed_list_items %}
		<li>{{item.name}} | {{item.description}}</li>
	{% endfor %}
	</ul>
	<!-- TODO: fix form so that completed items are not in the form -->
	{% if list.uncompleted_list_items%}
		<form action={% url 'todos:complete' list.id %} method="post">
		{%csrf_token%}
		{% for item in list.uncompleted_list_items %}
			<div>{{item.name}}:{{item.description}}
				<input type="checkbox" name="item" value="{{item.id}}"> Complete
			</div>
		{% endfor %}
		<input type="submit" value="Check off items">		
		</form>
	{% else %}
		<div>
			This list is completed!
		</div>
	{% endif %}
</div>

todos/templates/todos/index.html
{% if todo_lists%}
	<ul>
	{% for list in todo_lists %}
		<li><a href={% url 'todos:detail' list.id%}>{{list.title}}</a></li>
	{% endfor %}
	</ul>
{% else %}

	<p>There are no lists!</p>
{% endif %}